import { Box, Typography, Avatar } from "@mui/material";
import Image from "next/image";
import Signin from "./Signin.js";
import React from "react";
import Head from 'next/head'
export default function Home() {
  return (
    <Box>
       <Head>
        <title>SLippersZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <Box
        sx={{
          display: "flex",
          flexDirection: "row", 
          backgroundColor: "#F9F9F9",
        }} >
        <Image src="/Logo white.png" alt="logo" width={1900} height={600} />
        <Signin />
      </Box>

        <Box
         sx={{
           backgroundColor:"#000000",
          
        }}>
dad
        </Box>

    </Box>
  );
}
