import { Box, Typography, Avatar } from "@mui/material";
import Image from "next/image";
import Signin from "./Signin.js";
import React from "react";
import Head from "next/head";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>SLippersZone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          display: "flex",
          flexDirection: "row",
          height: "80px",
          backgroundColor: "#E0DECA",
          alignItems: "center",
        }}
      >
        <Typography 
          sx={{ 
            marginLeft: "10px", 
            fontFamily: "Impact Regular",
            fontSize:"35px" }}>
          SLippersZone
        </Typography>
        <Typography sx={{ marginLeft: "20px",fontFamily: "Diwani  Simple Outline 2 Regular",
            fontSize:"25px" }}>Log in</Typography>
      </Box>

      <Box
        sx={{
          display: "flex",
          flexDirection: "row",
          backgroundColor: "#FFFFFF",
        }}
      >
        <Image
          src="/prodImages/Logo white.png"
          alt="logo"
          width={1900}
          height={600}
        />
        <Signin />
      </Box>

      <Box
        sx={{
          backgroundColor: "#E0DECA",
        }}
      >
        dad
      </Box>
    </Box>
  );
}
